package com.earpopupx;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;

public final class MainActivity extends Activity{
 static final int REQ_BT=10,REQ_NOTIFY=11,REQ_MEDIA=12;TextView status,pos;SeekBar x,y,w,h,r,b,dim,dur;Switch auto,drag;
 @Override public void onCreate(Bundle b0){super.onCreate(b0);setContentView(R.layout.activity_main);bind();}
 private void bind(){status=findViewById(R.id.status);pos=findViewById(R.id.posLabel);findViewById(R.id.overlay).setOnClickListener(v->overlay());findViewById(R.id.bluetooth).setOnClickListener(v->bt());findViewById(R.id.notifications).setOnClickListener(v->notifyPerm());findViewById(R.id.battery).setOnClickListener(v->batteryOpt());findViewById(R.id.start).setOnClickListener(v->startMonitor());findViewById(R.id.stop).setOnClickListener(v->stopMonitor());findViewById(R.id.test).setOnClickListener(v->test());findViewById(R.id.pick).setOnClickListener(v->pick());findViewById(R.id.resetMedia).setOnClickListener(v->{AppPrefs.setMedia(this,null);Toast.makeText(this,"已恢复默认素材",Toast.LENGTH_SHORT).show();});findViewById(R.id.resetPopup).setOnClickListener(v->{AppPrefs.resetPopup(this);sync();refreshPopup();});
  auto=findViewById(R.id.autoSwitch);drag=findViewById(R.id.dragSwitch);auto.setChecked(AppPrefs.enabled(this));drag.setChecked(AppPrefs.dragMode(this));auto.setOnCheckedChangeListener((b0,c)->{AppPrefs.setEnabled(this,c);if(c)startMonitor();else stopMonitor();});drag.setOnCheckedChangeListener((b0,c)->{AppPrefs.setDragMode(this,c);refreshPopup();});
  x=findViewById(R.id.xBar);y=findViewById(R.id.yBar);w=findViewById(R.id.widthBar);h=findViewById(R.id.heightBar);r=findViewById(R.id.radiusBar);b=findViewById(R.id.blurBar);dim=findViewById(R.id.dimBar);dur=findViewById(R.id.durationBar);x.setMax(600);y.setMax(1000);w.setMax(26);h.setMax(400);r.setMax(64);b.setMax(80);dim.setMax(40);dur.setMax(28);sync();
  x.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setX(this,p-300)));y.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setY(this,p-500)));w.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setWidthPercent(this,p+72)));h.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setHeightDp(this,p+280)));r.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setRadiusDp(this,p)));b.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setBlurDp(this,p)));dim.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setDimPercent(this,p)));dur.setOnSeekBarChangeListener(sl((p,f)->AppPrefs.setDurationSec(this,p+2)));
 }
 interface S{void set(int p);}SeekBar.OnSeekBarChangeListener sl(S s){return new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar v,int p,boolean f){s.set(p);pos();if(f)refreshPopup();}public void onStartTrackingTouch(SeekBar v){}public void onStopTrackingTouch(SeekBar v){}};}
 void sync(){x.setProgress(AppPrefs.x(this)+300);y.setProgress(AppPrefs.y(this)+500);w.setProgress(AppPrefs.widthPercent(this)-72);h.setProgress(AppPrefs.heightDp(this)-280);r.setProgress(AppPrefs.radiusDp(this));b.setProgress(AppPrefs.blurDp(this));dim.setProgress(AppPrefs.dimPercent(this));dur.setProgress(AppPrefs.durationSec(this)-2);pos();}
 void pos(){pos.setText("X "+AppPrefs.x(this)+" · Y "+AppPrefs.y(this)+" · "+AppPrefs.widthPercent(this)+"% · "+AppPrefs.heightDp(this)+"dp · 圆角 "+AppPrefs.radiusDp(this)+"dp");}
 void overlay(){startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));}
 void bt(){if(Build.VERSION.SDK_INT>=31)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},REQ_BT);}
 void notifyPerm(){if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIFY);}
 void batteryOpt(){try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Throwable t){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_MEDIA);}
 @Override protected void onActivityResult(int r0,int c,Intent d){super.onActivityResult(r0,c,d);if(r0==REQ_MEDIA&&c==RESULT_OK&&d!=null&&d.getData()!=null){try{getContentResolver().takePersistableUriPermission(d.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Throwable ignored){}AppPrefs.setMedia(this,d.getData());refreshPopup();Toast.makeText(this,"素材已保存",Toast.LENGTH_SHORT).show();}}
 void startMonitor(){if(!Settings.canDrawOverlays(this)){overlay();Toast.makeText(this,"开启悬浮窗后再回来启动",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){bt();return;}AppPrefs.setEnabled(this,true);auto.setChecked(true);try{Intent i=new Intent(this,BluetoothMonitorService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);Toast.makeText(this,"耳机监听已启动",Toast.LENGTH_SHORT).show();}catch(Throwable t){Toast.makeText(this,"启动失败：请先在本页面保持可见并完成权限授权",Toast.LENGTH_LONG).show();}}
 void stopMonitor(){AppPrefs.setEnabled(this,false);auto.setChecked(false);try{stopService(new Intent(this,BluetoothMonitorService.class));}catch(Throwable ignored){}EarPopupWindow.shared(this).dismiss();}
 void test(){if(!Settings.canDrawOverlays(this)){overlay();return;}EarPopupWindow.shared(this).show("测试耳机 · EarPopup X",BatteryState.unknown("测试模式"));}
 void refreshPopup(){EarPopupWindow.shared(this).refreshLayout();}
 void status(){StringBuilder s=new StringBuilder();s.append(Settings.canDrawOverlays(this)?"● 悬浮窗已开启\n":"○ 悬浮窗未开启\n");if(Build.VERSION.SDK_INT>=31)s.append(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED?"● 蓝牙权限已开启\n":"○ 蓝牙权限未开启\n");if(Build.VERSION.SDK_INT>=33)s.append(checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED?"● 通知权限已开启\n":"○ 通知权限未开启\n");s.append(AppPrefs.enabled(this)?"● 自动弹窗已启用":"○ 自动弹窗未启用");status.setText(s.toString());}
 @Override protected void onResume(){super.onResume();status();}
}
